# Generated by Django 5.2.4 on 2025-07-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendar',
            name='accounting_calendar_company_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='chartofaccounts',
            name='accounting_chartofaccounts_company_account_key_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='territory',
            name='accounting_territory_company_territory_key_uniq',
        ),
        migrations.RenameIndex(
            model_name='generalledger',
            new_name='accounting__company_0fc102_idx',
            old_name='accounting_g_company_b8e5c8_idx',
        ),
        migrations.RenameIndex(
            model_name='generalledger',
            new_name='accounting__Account_548209_idx',
            old_name='accounting_g_account_e8b7a1_idx',
        ),
        migrations.RenameIndex(
            model_name='generalledger',
            new_name='accounting__Territo_511162_idx',
            old_name='accounting_g_territo_c5f2d4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('company', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together={('company', 'account_key')},
        ),
        migrations.AlterUniqueTogether(
            name='territory',
            unique_together={('company', 'territory_key')},
        ),
    ]
