# Generated by Django 5.2.4 on 2025-07-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_calendar_accounting_calendar_company_date_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Associated journal entry for this ledger entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounting.journalentry'),
        ),
    ]
